apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.basicwithrolerp.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  creds: {{ .Files.Get .Values.secret.basicwithrolerp.file | b64enc | quote }}
