apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.topic.name }}
  namespace: {{ .Values.namespace }}
spec:
  kafkaRestClassRef:
    name: krc-cfk
  replicas: {{ .Values.topic.replicas }}
  partitionCount: {{ .Values.topic.partitionCount }}
  configs:
    cleanup.policy: {{ .Values.topic.cleanupPolicy }}
