apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.credential.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  plainUsers: {{ .Files.Get .Values.secret.credential.plainUsers | b64enc | quote }}
  plainText: {{ .Files.Get .Values.secret.credential.plainText | b64enc | quote }}
  basicText: {{ .Files.Get .Values.secret.credential.basicText | b64enc | quote }}
